### ISSUE TITLE
まとめが削除できない

### ISSUE THREAD

**Issue by YumaInaura** [yukihirop/GrapeSlack#13]
PRが閉じてるので issue に上げておきます。

![image](https://cloud.githubusercontent.com/assets/13635059/26385233/007e9e22-4079-11e7-8093-b7b6a77e6198.png)

![image](https://cloud.githubusercontent.com/assets/13635059/26385229/f64b2696-4078-11e7-81cd-98957caeb24f.png)

**Comment by yukihirop** [comment]
削除できるように修正しましたが、プルリクはまだしません。

**Comment by yukihirop** [comment]
対応済み
